sudo: required
services:
  - docker

scripts:
  - docker build -t yer/ci-cd .
  - docker images yer/ci-cd

before-deploy:
  # - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

deploy:
  provider: script
  script: docker push yerx/travis-docker
  on:
    branch: master
