sudo: required
services:
  - docker

before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker build -t yerx/ci-cid .
  # - docker tag yerx/ci-cd yerx/ci-cd

# task to perform after the process is successful
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push yerx/ci-cd
